[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=(A=-2011270876,B=1182903154,C=-965786730,D=-1399474095)
ProjectName=AJB_PC_PORT
ProjectVersion=1.1.7.0
Description=A publicly available modkit designed for JJBA Last Survivor, created entirely by Aeyth8.
CompanyName=Aeyth8
CompanyDistinguishedName=Aeyth
Homepage="https://github.com/Aeyth8"
CopyrightNotice=
LicensingTerms=GNU AFFERO GENERAL PUBLIC LICENSE | Version 3, 19 November 2007
ProjectDisplayedTitle=

[/Script/UnrealEd.ProjectPackagingSettings]
UsePakFile=False
FullRebuild=False
bCookAll=True
+DirectoriesToNeverCook=(Path="/Game/AJB")
BuildConfiguration=PPBC_Development
IncludePrerequisites=False

[Staging]
;+WhitelistDirectories=/AJB/Content/Aeyth8/Textures/PlatformIcons/PS4
