[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=(A=-2011270876,B=1182903154,C=-965786730,D=-1399474095)
ProjectName=AJB_PC_PORT
ProjectVersion=1.1.7.0
Description=A publicly available modkit designed for JJBA Last Survivor, created entirely by Aeyth8.
CompanyName=Aeyth8
CompanyDistinguishedName=Aeyth
Homepage="https://github.com/Aeyth8"
CopyrightNotice=
LicensingTerms=GNU AFFERO GENERAL PUBLIC LICENSE | Version 3, 19 November 2007
ProjectDisplayedTitle=

[Staging]
;+WhitelistDirectories=/AJB/Content/Aeyth8/Textures/PlatformIcons/PS4

[/Script/UnrealEd.ProjectPackagingSettings]
Build=IfProjectHasCode
BuildConfiguration=PPBC_Development
StagingDirectory=(Path="C:/Users/Jay/Documents/Unreal Projects/JoJoTheMoonBear/AJB_PROD/Packaged/Aftermath")
FullRebuild=False
ForDistribution=False
IncludeDebugFiles=False
BlueprintNativizationMethod=Disabled
bIncludeNativizedAssetsInProjectGeneration=False
bExcludeMonolithicEngineHeadersInNativizedCode=False
UsePakFile=False
bGenerateChunks=False
bGenerateNoChunks=False
bChunkHardReferencesOnly=False
bBuildHttpChunkInstallData=False
HttpChunkInstallDataDirectory=(Path="")
HttpChunkInstallDataVersion=
IncludePrerequisites=False
IncludeAppLocalPrerequisites=False
bShareMaterialShaderCode=False
bSharedMaterialNativeLibraries=False
ApplocalPrerequisitesDirectory=(Path="")
IncludeCrashReporter=False
InternationalizationPreset=English
-CulturesToStage=en
+CulturesToStage=en
bCookAll=True
bCookMapsOnly=False
bCompressed=False
bEncryptIniFiles=False
bEncryptPakIndex=False
bSkipEditorContent=False
bSkipMovies=False
+DirectoriesToNeverCook=(Path="/Game/Aeyth8/NEVER_COOK")
bNativizeBlueprintAssets=False
bNativizeOnlySelectedBlueprints=False

